### ISSUE TITLE
大佬数据库怎么搞的，我想把项目跑起来

### ISSUE THREAD

**Issue by xiaoximvp** [kixuan/RedisProject_hmdp#12]
Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

**Comment by xiaoximvp** [comment]
打扰了，我搞定了

**Comment by kixuan** [comment]
好的搞定就好！看报错应该是数据库的url没配置好，我的是3307端口的

**Comment by kixuan** [comment]
好的搞定就好！看报错应该是数据库的url没配置好，我的是3307端口的
